name: gh pages upload

on:
  push:
    branches:
      - main
      - gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Packages install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build:gh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.2.0
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
